name: 🏁 Windows Builds
on: 
  push:
  pull_request:
  schedule:
    - cron: "0 */6 * * *" #cron is going to make me an unhinged madman

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_BASE_BRANCH: 3.4
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no profile=custom.py
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: windows-editor
            target: release_debug
            tools: true
            bin: "./bin/godot.windows.tools.64.emmerson.exe"

          - name: Template (target=release, tools=no)
            cache-name: windows-template
            target: release
            tools: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: windows
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          scons-cache-limit: 3072

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
